include:
  - ./docker-compose.base.yml
  
services:
  graph-node:
    # image: lotaway/graph-node
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: graph-node
    container_name: default-graph-node
    ports:
      - "${GRAPH_NODE_PORT:-8000}:8000"
      - "${GRAPH_NODE_DEBUG_PORT:-8001}:8001"
      - "${GRAPH_NODE_ADMIN_PORT:-8020}:8020"
      - "${GRAPH_NODE_INDEXER_PORT:-8030}:8030"
      - "${GRAPH_NODE_QUERY_PORT:-8040}:8040"
    depends_on:
      - graph-ipfs
      - graph-postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: graph-postgres
      postgres_user: ${GRAPH_POSTGRES_USER:-admin}
      postgres_pass: ${GRAPH_POSTGRES_PASSWORD:-123123}
      postgres_db: ${GRAPH_POSTGRES_DB:-graph-node}
      ipfs: "graph-ipfs:5001"
      ethereum: "base:https://base-rpc.publicnode.com"
      GRAPH_LOG: error
    networks:
      - default-base-graph